robotont fake rviz
robotont/robotont_support pull request #1
Opened 2020-02-06 17:50 UTC by iharsuvorau

That's the fake odom with rzviz stuff.

2020-02-06 18:06 UTC, RValner requested changes
Refer to the comments.

2020-02-06 18:06 UTC, RValner commented on CMakeLists.txt
> +# add_compile_options(-std=c++11)
Uncomment the std c++11 compile options.

2020-02-06 18:06 UTC, RValner commented on CMakeLists.txt
> +## System dependencies are found with CMake's conventions
Remove all the unnecessary commented junk. But don't remove "catkin_package(..." while you are doing that.

2020-02-06 18:06 UTC, RValner commented on package.xml
> +  <!-- Url tags are optional, but multiple are allowed, one per tag -->
Same here, remove all unnecessary comments.

2020-02-06 18:18 UTC, iharsuvorau commented
@RValner Check this e41e653.

2020-08-09 20:16 UTC, Veix123 commented
Fake driver moved under https://github.com/robotont/robotont_driver repo.

2020-08-09 20:16 UTC, closed without merging